name: Dependency Audit

on:
  schedule:
    - cron: '0 3 * * 1' # Runs every Monday at 3:00 AM UTC
  workflow_dispatch:

jobs:
  audit-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run depcheck
        run: npx depcheck --json > depcheck-report.json

      - name: Create GitHub issue for unused dependencies
        id: create-issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Dependency Audit Report"
          content-filepath: depcheck-report.json
          labels: "dependency, audit"